/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/speakingPerson.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Text001.geometry} material={materials.text} position={[0.53, 1.9, 0.15]} rotation={[Math.PI / 2, 0, 0]} scale={0.19} />
      <group position={[0, 1.34, 0.02]} rotation={[0, 0.46, 0]} scale={[0.17, 0.21, 0.19]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.skin} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.innerMouth} />
      </group>
      <mesh geometry={nodes.hair.geometry} material={materials.hair} position={[0, 1.34, 0.02]} rotation={[0, 0.46, 0]} scale={[0.17, 0.21, 0.19]} />
      <mesh geometry={nodes.eyes.geometry} material={materials.eyes} position={[0.11, 1.37, 0.14]} rotation={[0, 0.46, 0]} scale={[-0.01, -0.02, -0.01]} />
      <mesh geometry={nodes.nose.geometry} material={materials.skin} position={[0.08, 1.34, 0.18]} rotation={[0, 0.46, 0]} scale={[0.01, -0.02, 0.01]} />
      <mesh geometry={nodes.teeth1.geometry} material={materials.teeth} position={[0.07, 1.3, 0.17]} rotation={[0, 0.46, 0]} scale={[0.06, -0.01, 0.01]} />
      <mesh geometry={nodes.teeth2.geometry} material={materials.teeth} position={[0.07, 1.25, 0.16]} rotation={[0, 0.46, Math.PI]} scale={[0.04, -0.01, 0.01]} />
      <mesh geometry={nodes.tongue.geometry} material={materials.tongue} position={[0.04, 1.25, 0.11]} rotation={[0, 0.46, 0]} scale={[0.04, -0.02, 0.04]} />
      <mesh geometry={nodes.body.geometry} material={materials.skin} position={[0, 0, 0.01]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.skin} position={[0.17, 1.36, 0.02]} rotation={[1.49, -0.17, -0.47]} scale={[0.03, -0.02, 0.04]} />
      <group position={[0, -0.08, 0.02]} scale={[-0.07, 0.52, -0.07]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.jeans} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.skin} />
      </group>
      <mesh geometry={nodes.jumper.geometry} material={materials.jumper} position={[0, 0, 0.01]} />
      <mesh geometry={nodes.eyebrow1.geometry} material={materials.hair} position={[0.11, 1.39, 0.16]} rotation={[-0.7, 0.8, 2.05]} scale={[0.64, 0.96, 0.7]} />
      <mesh geometry={nodes.eyebrow2.geometry} material={materials.hair} position={[0.04, 1.39, 0.17]} rotation={[-2.47, -0.46, -1.34]} scale={[0.64, 0.96, 0.7]} />
      <mesh geometry={nodes.trousers.geometry} material={materials.jeans} position={[-0.01, 0.44, 0.01]} scale={0.15} />
      <mesh geometry={nodes.speech_balloon.geometry} material={materials['speech balloon']} position={[0.96, 1.76, 0.05]} rotation={[1.57, 0, 0]} scale={[0.58, 0.08, 0.58]} />
      <group position={[-0.09, -0.71, 0.02]} scale={0.29}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.Base} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Base} position={[0, 0.09, 0.34]} scale={1.25} />
        <mesh geometry={nodes.Cube002.geometry} material={materials['Inner Shoe']} position={[0, 0.25, -0.03]} scale={[0.87, 1.06, 0.87]} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Inner Shoe']} position={[0.56, 0.25, -0.03]} scale={[0.87, 1.06, 0.87]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.Base} position={[0.57, 0.09, 0.34]} scale={1.25} />
        <mesh geometry={nodes.NurbsPath.geometry} material={materials.Lace} position={[0, -0.07, 0.47]} rotation={[1.51, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath001.geometry} material={materials.Lace} position={[0, -0.05, 0.39]} rotation={[1.64, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath002.geometry} material={materials.Lace} position={[0, 0, 0.29]} rotation={[1.97, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.NurbsPath003.geometry} material={materials.Lace} position={[0, 0.09, 0.22]} rotation={[2.42, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.NurbsPath004.geometry} material={materials.Lace} position={[0.57, -0.07, 0.47]} rotation={[1.51, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath005.geometry} material={materials.Lace} position={[0.57, -0.05, 0.39]} rotation={[1.64, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath006.geometry} material={materials.Lace} position={[0.57, 0, 0.29]} rotation={[1.97, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.NurbsPath007.geometry} material={materials.Lace} position={[0.57, 0.09, 0.22]} rotation={[2.42, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-0.05, -0.31, 0.54]} rotation={[-Math.PI, -1.57, 0]} scale={0.19} />
      </group>
    </group>
  )
}

useGLTF.preload('/speakingPerson.gltf')
