/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/workingPerson.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={5}>
      <group position={[-0.14, 1.04, -1.06]} rotation={[0.32, 0, -0.01]} scale={[0.17, 0.21, 0.19]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.skin} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.innerMouth} />
      </group>
      <mesh geometry={nodes.hair.geometry} material={materials.hair} position={[-0.14, 1.04, -1.06]} rotation={[0.32, 0, -0.01]} scale={[0.17, 0.21, 0.19]} />
      <mesh geometry={nodes.eyes.geometry} material={materials.eyes} position={[-0.09, 1, -0.89]} rotation={[0.32, 0, -0.01]} scale={[-0.01, -0.02, -0.01]} />
      <mesh geometry={nodes.nose.geometry} material={materials.skin} position={[-0.14, 0.98, -0.89]} rotation={[0.32, 0, -0.01]} scale={[0.01, -0.02, 0.01]} />
      <mesh geometry={nodes.teeth1.geometry} material={materials.teeth} position={[-0.14, 0.93, -0.93]} rotation={[0.32, 0, -0.01]} scale={[0.06, -0.01, 0.01]} />
      <mesh geometry={nodes.teeth2.geometry} material={materials.teeth} position={[-0.14, 0.91, -0.94]} rotation={[0.32, 0, 3.13]} scale={[0.04, -0.01, 0.01]} />
      <mesh geometry={nodes.tongue.geometry} material={materials.tongue} position={[-0.14, 0.92, -0.99]} rotation={[0.32, 0, -0.01]} scale={[0.04, -0.02, 0.04]} />
      <mesh geometry={nodes.body.geometry} material={materials.skin} position={[-0.14, -0.28, -1.25]} rotation={[0.12, 0, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.skin} position={[0.02, 1.03, -0.98]} rotation={[1.9, -0.2, 0.01]} scale={[0.03, -0.02, 0.04]} />
      <group position={[0, -0.08, 0.02]} scale={[-0.07, 0.52, -0.07]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.jeans} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.skin} />
      </group>
      <mesh geometry={nodes.jumper.geometry} material={materials.jumper} position={[-0.14, -0.28, -1.25]} rotation={[0.12, 0, 0]} />
      <mesh geometry={nodes.eyebrow1.geometry} material={materials.hair} position={[-0.1, 1.03, -0.87]} rotation={[-0.18, 0.42, 1.73]} scale={[0.64, 0.96, 0.7]} />
      <mesh geometry={nodes.eyebrow2.geometry} material={materials.hair} position={[-0.17, 1.04, -0.9]} rotation={[-2.22, -0.08, -1.62]} scale={[0.64, 0.96, 0.7]} />
      <mesh geometry={nodes.trousers.geometry} material={materials.jeans} position={[-0.15, 0.15, -1.12]} scale={0.15} />
      <mesh geometry={nodes.logoPc.geometry} material={materials.logo} position={[-0.15, 0.32, -0.39]} rotation={[0.11, 0, 0]} scale={[0.04, 0.04, 0]} />
      <mesh geometry={nodes.laptop.geometry} material={materials.laptop} position={[-0.16, 0.13, -0.62]} rotation={[0.11, 0, 0]} scale={[0.24, 0.01, 0.19]} />
      <mesh geometry={nodes.laptopScreen.geometry} material={materials.laptop} position={[-0.16, 0.31, -0.41]} rotation={[1.68, 0, 0]} scale={[0.24, 0.01, 0.19]} />
      <group position={[-0.23, -0.56, -0.6]} scale={0.28}>
        <mesh geometry={nodes.Cube017.geometry} material={materials['Base.001']} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['Rubber.001']} />
        <mesh geometry={nodes.Cube001.geometry} material={materials['Base.001']} position={[0, 0.09, 0.34]} scale={1.25} />
        <mesh geometry={nodes.Cube002.geometry} material={materials['Inner Shoe.001']} position={[0, 0.25, -0.03]} scale={[0.87, 1.06, 0.87]} />
        <mesh geometry={nodes.NurbsPath.geometry} material={materials['Lace.001']} position={[0, -0.07, 0.47]} rotation={[1.51, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath001.geometry} material={materials['Lace.001']} position={[0, -0.05, 0.39]} rotation={[1.64, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath002.geometry} material={materials['Lace.001']} position={[0, 0, 0.29]} rotation={[1.97, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.NurbsPath003.geometry} material={materials['Lace.001']} position={[0, 0.09, 0.22]} rotation={[2.42, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-0.05, -0.31, 0.54]} rotation={[-Math.PI, -1.57, 0]} scale={0.19} />
      </group>
      <group position={[-0.23, -0.56, -0.6]} scale={0.28}>
        <mesh geometry={nodes.Cube020.geometry} material={materials['Base.001']} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['Rubber.001']} />
      </group>
      <group position={[-0.06, -0.56, -0.6]} scale={0.28}>
        <mesh geometry={nodes.Cube021.geometry} material={materials['Base.001']} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials['Rubber.001']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Base.001']} position={[0, 0.09, 0.34]} scale={1.25} />
        <mesh geometry={nodes.Cube004.geometry} material={materials['Inner Shoe.001']} position={[0, 0.25, -0.03]} scale={[0.87, 1.06, 0.87]} />
        <mesh geometry={nodes.NurbsPath004.geometry} material={materials['Lace.001']} position={[0, -0.07, 0.47]} rotation={[1.51, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath005.geometry} material={materials['Lace.001']} position={[0, -0.05, 0.39]} rotation={[1.64, 0, 0]} scale={[0.08, 0.08, 0.09]} />
        <mesh geometry={nodes.NurbsPath006.geometry} material={materials['Lace.001']} position={[0, 0, 0.29]} rotation={[1.97, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.NurbsPath007.geometry} material={materials['Lace.001']} position={[0, 0.09, 0.22]} rotation={[2.42, 0, 0]} scale={[0.08, 0.08, 0.1]} />
        <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[-0.05, -0.31, 0.54]} rotation={[-Math.PI, -1.57, 0]} scale={0.19} />
      </group>
      <group position={[-0.06, -0.56, -0.6]} scale={0.28}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['Base.001']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Rubber.001']} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.bench} position={[-0.14, -0.32, -1.22]} scale={[0.73, 0.3, 0.25]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.cloud} position={[0.31, 0.65, -0.39]} scale={[0.14, 0.1, 0.03]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.cloudBalk} position={[0.32, 0.69, -0.36]} scale={[0.09, 0.01, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.cloudBalk} position={[0.32, 0.66, -0.36]} scale={[0.09, 0.01, 0]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.cloudBalk} position={[0.32, 0.61, -0.36]} scale={[0.09, 0.01, 0]} />
    </group>
  )
}

useGLTF.preload('/workingPerson.gltf')
